"""weekly email logs

Revision ID: 0b9f146c165a
Revises: 432783cda776
Create Date: 2025-09-06 20:29:48.785635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9f146c165a'
down_revision = '432783cda776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_email_log_week'), ['week'], unique=True)

    op.create_table('weekly_email_recipient_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['weekly_email_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_email_recipient_log', schema=None) as batch_op:
        batch_op.create_index('ix_recipient_log_logid_email', ['log_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_email_recipient_log_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_email_recipient_log_log_id'), ['log_id'], unique=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_week'))

    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pick_game'))
        batch_op.drop_index(batch_op.f('ix_pick_user'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pick_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pick_game'), ['game_id'], unique=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_week'), ['week'], unique=False)

    with op.batch_alter_table('weekly_email_recipient_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_email_recipient_log_log_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_email_recipient_log_email'))
        batch_op.drop_index('ix_recipient_log_logid_email')

    op.drop_table('weekly_email_recipient_log')
    with op.batch_alter_table('weekly_email_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_email_log_week'))

    op.drop_table('weekly_email_log')
    # ### end Alembic commands ###
