"""Add spread_is_locked & spread_locked_at to Game

Revision ID: 2c667c57e246
Revises: 663511632671
Create Date: 2025-08-14 15:26:59.140777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c667c57e246'
down_revision = '663511632671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spread_is_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('spread_locked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('spread',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_game_odds_event_id'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_game_odds_event_id'), ['odds_event_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('spread',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('spread_locked_at')
        batch_op.drop_column('spread_is_locked')

    # ### end Alembic commands ###
