"""Drop user.full_name; make game.odds_event_id unique

Revision ID: 432783cda776
Revises: 37aa17390959
Create Date: 2025-08-26 15:11:14.025112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432783cda776'
down_revision = '37aa17390959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_game_match_kickoff'))
        batch_op.drop_index(batch_op.f('ux_game_odds_event_id'))
        batch_op.create_index(batch_op.f('ix_game_odds_event_id'), ['odds_event_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_odds_event_id'))
        batch_op.create_index(batch_op.f('ux_game_odds_event_id'), ['odds_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ux_game_match_kickoff'), ['home_team', 'away_team', 'kickoff_at'], unique=True)

    # ### end Alembic commands ###
