"""add season.uses_week19

Revision ID: 922208256889
Revises: 277997558802
Create Date: 2026-09-01 12:40:04.598415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922208256889'
down_revision = '277997558802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_week19', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('uses_week19')

    # ### end Alembic commands ###
