"""Drop start_time from Game

Revision ID: 9a7a5bf62516
Revises: f91beedf1161
Create Date: 2025-08-21 11:25:29.005916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a7a5bf62516'
down_revision = 'f91beedf1161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
