"""Add is_admin (default false) and full_name to user

Revision ID: def63b9542ec
Revises: fa9a9854fe3b
Create Date: 2025-08-13 22:13:51.024173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def63b9542ec'
down_revision = 'fa9a9854fe3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_admin with a server_default so existing rows pass NOT NULL
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))

    # Add full_name (nullable is fine)
    op.add_column('user', sa.Column('full_name', sa.String(length=120), nullable=True))

    # Drop the server_default so future inserts rely on ORM default / explicit value
    op.alter_column('user', 'is_admin', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'is_admin')

    # ### end Alembic commands ###
