"""add notifications and paid status to User

Revision ID: e1d3f13d84a4
Revises: ef7febe10b72
Create Date: 2025-08-26 11:46:26.851808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d3f13d84a4'
down_revision = 'ef7febe10b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_lines_posted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_picks_reminder', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_weekly_recap', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_weekly_recap')
        batch_op.drop_column('notify_picks_reminder')
        batch_op.drop_column('notify_lines_posted')
        batch_op.drop_column('entry_paid')


    # ### end Alembic commands ###
