"""Add bookmaker_spreads and chosen spread columns

Revision ID: e3e6f7d709d1
Revises: def63b9542ec
Create Date: 2025-08-14 09:53:43.216173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e6f7d709d1'
down_revision = 'def63b9542ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bookmaker_spreads',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('game_id', sa.Integer(), sa.ForeignKey('game.id', ondelete='CASCADE'), nullable=False),
        sa.Column('bookmaker_key', sa.Text(), nullable=False),
        sa.Column('bookmaker_title', sa.Text(), nullable=False),
        sa.Column('home_point', sa.Numeric(), nullable=True),
        sa.Column('away_point', sa.Numeric(), nullable=True),
        sa.Column('home_price', sa.Numeric(), nullable=True),
        sa.Column('away_price', sa.Numeric(), nullable=True),
        sa.Column('last_update', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint('game_id', 'bookmaker_key', name='uq_bookmaker_spreads_game_bookmaker')
    )

    op.add_column('game', sa.Column('spread_home', sa.Numeric(), nullable=True))
    op.add_column('game', sa.Column('spread_away', sa.Numeric(), nullable=True))
    op.add_column('game', sa.Column('spread_source', sa.Text(), nullable=True))
    op.add_column('game', sa.Column('spread_bookmaker_key', sa.Text(), nullable=True))
    op.add_column('game', sa.Column('spread_last_update', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'spread_last_update')
    op.drop_column('game', 'spread_bookmaker_key')
    op.drop_column('game', 'spread_source')
    op.drop_column('game', 'spread_away')
    op.drop_column('game', 'spread_home')
    op.drop_table('bookmaker_spreads')
    # ### end Alembic commands ###
