"""email kind

Revision ID: fecfc6fd2370
Revises: 0b9f146c165a
Create Date: 2025-09-07 06:29:10.088663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecfc6fd2370'
down_revision = '0b9f146c165a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_email_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=32), server_default='weekly', nullable=False))
        batch_op.drop_index(batch_op.f('ix_weekly_email_log_week'))
        batch_op.create_index(batch_op.f('ix_weekly_email_log_week'), ['week'], unique=False)
        batch_op.create_unique_constraint('uq_week_kind', ['week', 'kind'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_email_log', schema=None) as batch_op:
        batch_op.drop_constraint('uq_week_kind', type_='unique')
        batch_op.drop_index(batch_op.f('ix_weekly_email_log_week'))
        batch_op.create_index(batch_op.f('ix_weekly_email_log_week'), ['week'], unique=True)
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
